# Site Settings
baseurl: ""
url : "https://dynamic-iterative-process.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : dynamiciterativeprocess
    description : Naomi Pereira's Data Protfolio
    skill : Python, SQL , Jupyter Notebook
    location : London, United Kingdom
    Domain: Aspiring Data Analyst with a passion for Finance & Tech
        
  # Icons
  icons :
    email:  naomipereira1810@gmail.com
    linkedin: https://www.linkedin.com/in/n-pereira-a8bb8523a/
    github: dynamiciterativeprocess
    phone: +44 7436363808

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: 
  - jekyll-paginate # Added 'jekyll-paginate' gem
bootstrap:
  assets: true
